### ISSUE TITLE
Better handling of spaces

### ISSUE THREAD

**Issue by KathleenDollard** [AlessandroDelSole/CodeSnippetStudio#14]
This may be the same as the word selection issue, but it is a specific scenario that feels a bit different. 

Because spaces aren't trimmed off the end of the replacement word, it is very, very easy for the following code to have issues if typename1 and typename2 have spaces following them. 

public Class1(typename1 param1, typename2 param2)
{
    prop1 = param1;
    prop2 = param2;
}
public typename1 prop1 { get; }
public typename2 prop2 { get; }

resulting in 

  public Class1(typename1param1, typename2param2)
        {
            prop1 = param1;
            prop2 = param2;
        }
        public typename1prop1 { get; }
    public typename2prop2 { get; }

**Comment by AlessandroDelSole** [comment]
Thanks for the feedback, Kathleen. I'll be working on fixing this very soon.

**Comment by AlessandroDelSole** [comment]
Hi Kathleen,
I've published an updated extension that addresses this. Please let me know if it is okay or feel free to reopen the issue.

Please notice that only the VS extension has been updated so far, the stand-alone app will be updated shortly.
