### ISSUE TITLE
Font color

### ISSUE THREAD

**Issue by maxisam** [AlessandroDelSole/CodeSnippetStudio#16]
Is there a way to change font color ?

I am using a dark theme, but somehow it doesn't really work in Snippet Studio.

The background doesn't turn dark but the font color becomes white. 

I wonder if there is a setting to fix it.

Thanks

**Comment by AlessandroDelSole** [comment]
Hi,
theming is based on an external component from Syncfusion so I have to investigate this further. By the way, I've noticed this workaround:
1. Select the dark theme for Studio
2. If it's not applied, select another theme, then select again the dark theme (or the one you like)

This should temporarily solve. Thanks for reporting this.

**Comment by AlessandroDelSole** [comment]
I have just released version 1.3.8 on the Visual Studio Gallery (and the source code has been updated), which introduces color pickers for text, selection, and selection background, plus update themes. Please download the updated extension and give it a try. Feel free to re-open the issue if it is not solved.
