### ISSUE TITLE
Crashes visual studio when importing a .vsi

### ISSUE THREAD

**Issue by yvdh** [AlessandroDelSole/CodeSnippetStudio#17]
Hi,

Crashes visual studio when importing or converting a .vsi. 
VS2015 Enterprise, 64-bit on Windows 10.

Cheers

**Comment by AlessandroDelSole** [comment]
Thanks for reporting this. I'll investigate the DelSole.VSIX library which empowers that feature. I'll keep you updated.

**Comment by AlessandroDelSole** [comment]
I have fixed an issue on malformed pathnames when importing .vsi archives. Please update to version 1.4 and let me know if it works. Feel free to reopen the issue if the problem still appears. Thanks.
