### ISSUE TITLE
It is difficult to resize the code block

### ISSUE THREAD

**Issue by micdenny** [AlessandroDelSole/CodeSnippetStudio#6]
I uploaded a video to show you the behavior I get: http://screencast.com/t/UzRpRJaH

Basically the right splitter of the central code block does not resize well on the right, it moves slowly, but it's better to see the video to get what I'm talking about ;)

The second minor problem is that the splitter is so small that is difficult to use it.

**Comment by AlessandroDelSole** [comment]
Thanks for getting in touch. Yes, resizing the code editor area must be improved but this currently happens only in the extension for Visual Studio. If you try the stand-alone application it works as expected. 

About the splitter, it is provided by the DockingManager control from the Syncfusion's Essential for WPF so I have to investigate if you can change its layout and behavior. 

Thanks!

**Comment by micdenny** [comment]
yes the standalone works like a sharm ;)

**Comment by AlessandroDelSole** [comment]
The issue has been resolved. Please update the extension to version 1.2.7. Thanks.

**Comment by micdenny** [comment]
@AlessandroDelSole ops, I took this exception with the latest version 1.2.7

![image](https://cloud.githubusercontent.com/assets/1633595/12331407/a901f7ae-bae9-11e5-9f5b-2282e5bcce54.png)

I simply run it from here (same if I try to run it from menu):

![image](https://cloud.githubusercontent.com/assets/1633595/12331447/da18f4a0-bae9-11e5-973c-76835715748a.png)

**Comment by micdenny** [comment]
Tried to `devenv /log` but the resulted `activitylog.xml` does not show anything useful:

![image](https://cloud.githubusercontent.com/assets/1633595/12331671/d0bd2b32-baea-11e5-9ca7-061f7c0f5e13.png)

no error before, after or between the loading of assembly

if I can check other log files just tell me and I will check it

**Comment by AlessandroDelSole** [comment]
Would you be so kind to uninstall the extension, restart VS and reinstall it? Thanks!

**Comment by micdenny** [comment]
nothing, again the error, I try to also reboot, maybe some files were locked by system when updating, dunno...

**Comment by AlessandroDelSole** [comment]
Ok, thanks. I see there's an assembly mismatch between the stand-alone app and the extension, so I'm uploading version 1.2.8 right now. I hope this solves the issue.

**Comment by micdenny** [comment]
so you mean that the stand-alone app is conflicting with the vs extension? 

should they be upgraded together or can they have different version without problem?

**Comment by micdenny** [comment]
v1.2.8 works! just tested, thank you :smile:

**Comment by AlessandroDelSole** [comment]
Perfect! The problem was simply a bad assembly reference to a Syncfusion control in the extension counterpart.. Sorry about the inconvenience
