### ISSUE TITLE
How to work with custom functions?

### ISSUE THREAD

**Issue by nzain** [AlessandroDelSole/CodeSnippetStudio#7]
Is it possible to autocompute other placeholders? Think of

public type PropertyName {
  get { return this._backingField; }
  set { this._backingField = value; }
}

When using such a snippet, you want to specify the type and the uppercase propertyname, but the backing field should be PropertyName with the first char.ToLower() plus an underscore.

There is actually a field called "Function", but I couldn't find any documentation on this.

**Comment by AlessandroDelSole** [comment]
Are you talking about the code editor's IntelliSense? If so, it's built-in the Syntax Edit control from Syncfusion. Would you please clarify a bit where this should be accomplished? thanks.

**Comment by nzain** [comment]
Sorry for not being clear. I'm talking about "derived" placeholders. In snippet studio I would specify some special function that computes the value of placeholder2 based on another placeholder, say placeholder1. When using that snippet in Visual Studio, I would only enter placeholder1, while the other one gets automatically computed.

Actually, I'm not even sure if the .snippets format supports this. I've been using Resharper and their snippet manager, which has this feature. However, in your snippet studio, in the placeholder list, there is a field "function". This sounds exactly like such a feature, but I don't know how to use it.

**Comment by AlessandroDelSole** [comment]
Ok, I got it now. "Function" is not a real function, it's just a field name consistent with the XML schema for IntelliSense code snippets. Such a schema does not support derived placeholders, but I will see if there's a way to implement this in Studio. Thanks.
