### ISSUE TITLE
CodeSnippetStudio standalone download 

### ISSUE THREAD

**Issue by midiway** [AlessandroDelSole/CodeSnippetStudio#8]
Where can I download the CodeSnippetStudio standalone .exe?

**Comment by AlessandroDelSole** [comment]
The home page has a link to the standalone application: https://codesnippetstudio.codeplex.com/downloads/get/clickOnce/CodeSnippetStudio.application

**Comment by midiway** [comment]
your .application gives error: 
![](https://cloud.githubusercontent.com/assets/493743/15248698/fd639e9a-18f1-11e6-90f0-5775cc7c67e2.png)
Also, I would prefer a portable .zip with the .exe than that installer.

**Comment by AlessandroDelSole** [comment]
Do you have the .NET Framework 4.6 installed on your machine?

**Comment by midiway** [comment]
yes

**Comment by midiway** [comment]
4.6.1 actually

**Comment by AlessandroDelSole** [comment]
What if you click Details? can you provide the info?
By the way, you can download the source code, build the solution in Visual Studio 2015 and zip what you like.

**Comment by midiway** [comment]
ahh, that was obvious, it was my firewall, I don't know what application handles this .application thing, but it was blocked here somehow..
that's why distributing a portable/downloadable .zip is a better option

I tried compiling, but got many error, so gave up
